/* Secure bridge between the local finance data and the Public portfolio endpoint. */
(function(root,factory){
  var api=factory();
  if(typeof module!=="undefined"&&module.exports) module.exports=api;
  else { root.PublicSync=api; api.configure(root); }
})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  var SUPABASE_URL="https://qtmjogfivvwivenoiczx.supabase.co";
  var SUPABASE_KEY="sb_publishable_sFR-ur1OZZxIkwFjuMXsJQ_ncA77AAC";
  var LAST_SYNC_KEY="finanzas_public_last_sync_v1",EMAIL_KEY="finanzas_public_email_v1",TRM_SYNC_KEY="finanzas_trm_last_sync_v1",FIFTEEN_MINUTES=15*60*1000,SIX_HOURS=6*60*60*1000;
  var TRM_URL="https://www.datos.gov.co/resource/32sa-8pi3.json?$limit=1&$order=vigenciadesde%20DESC";
  var rootWindow=null,app=null,busy=false,message="",session=null;
  function number(value){var parsed=Number(value);return Number.isFinite(parsed)?parsed:0;}
  function normalized(value){return String(value||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");}
  function typeFor(value){value=String(value||"").toUpperCase();if(value.indexOf("CRYPTO")>=0)return "Cripto";if(value.indexOf("ETF")>=0||value.indexOf("FUND")>=0)return "ETF";if(value==="CASH")return "Efectivo";return "Acción";}
  function similar(existing,position){var oldName=normalized(existing.name),symbol=normalized(position.symbol),fullName=normalized(position.name);if(!oldName)return false;return oldName===symbol||oldName===fullName||(oldName.length>3&&fullName.indexOf(oldName)>=0)||(fullName.length>3&&oldName.indexOf(fullName)>=0);}
  function flattenAccounts(accounts){var out=[];(accounts||[]).forEach(function(account){var accountId=String(account.accountId||"");(account.positions||[]).forEach(function(position){var instrument=position.instrument||{},symbol=String(instrument.symbol||instrument.name||"Posición");out.push({externalKey:accountId+":"+symbol+":"+String(instrument.type||""),symbol:symbol,name:String(instrument.name||symbol),type:typeFor(instrument.type),qty:number(position.quantity),currentValue:number(position.currentValue),costBase:number(position.costBasis&&position.costBasis.totalCost),currency:"USD",publicAccountType:String(account.accountType||"")});});var cash=number(account.cash);if(cash>0)out.push({externalKey:accountId+":CASH",symbol:"CASH",name:"Public · Efectivo",type:"Efectivo",qty:cash,currentValue:cash,costBase:cash,currency:"USD",publicAccountType:String(account.accountType||"")});});return out;}
  function mergePositions(existing,accounts,idFactory){var incoming=flattenAccounts(accounts),manual=(existing||[]).filter(function(i){return i.provider!=="Public";}),linked=(existing||[]).filter(function(i){return i.provider==="Public";}),result=manual.slice();incoming.forEach(function(position){var match=linked.filter(function(i){return i.externalKey===position.externalKey;})[0];if(!match)match=result.filter(function(i){return i.provider!=="Public"&&similar(i,position);})[0];var next=Object.assign({},match||{},position,{id:(match&&match.id)||(idFactory?idFactory():"public-"+position.externalKey),name:position.symbol==="CASH"?position.name:(position.symbol||position.name),provider:"Public",syncedAt:new Date().toISOString()});if(match){var index=result.indexOf(match);if(index>=0)result[index]=next;else result.push(next);}else result.push(next);});return result;}
  function safeGet(key){try{return localStorage.getItem(key)||"";}catch(e){return "";}}
  function safeSet(key,value){try{localStorage.setItem(key,value);}catch(e){}}
  function safeDel(key){try{localStorage.removeItem(key);}catch(e){}}
  var SESSION_KEY="finanzas_public_session_v1";
  function request(url,options){
    options=options||{};
    return new Promise(function(resolve,reject){
      var xhr=new XMLHttpRequest();
      xhr.open(options.method||"GET",url,true);
      Object.keys(options.headers||{}).forEach(function(key){xhr.setRequestHeader(key,options.headers[key]);});
      xhr.onload=function(){var data=null;try{data=xhr.responseText?JSON.parse(xhr.responseText):null;}catch(e){}resolve({ok:xhr.status>=200&&xhr.status<300,status:xhr.status,data:data,text:xhr.responseText||""});};
      xhr.onerror=function(){reject(new Error("Network error"));};
      xhr.send(options.body||null);
    });
  }
  function saveSession(value){session=value||null;if(session)safeSet(SESSION_KEY,JSON.stringify(session));else safeDel(SESSION_KEY);if(app)app.setSession(session);}
  function readSession(){try{return JSON.parse(safeGet(SESSION_KEY))||null;}catch(e){return null;}}
  function encodeSession(value){if(!value||!value.access_token||!value.refresh_token)throw new Error("Sesión incompleta");return btoa(JSON.stringify({v:1,access_token:value.access_token,refresh_token:value.refresh_token,expires_at:number(value.expires_at),expires_in:number(value.expires_in)||3600,token_type:value.token_type||"bearer"}));}
  function decodeSession(code){var value=JSON.parse(atob(String(code||"").trim()));if(value.v!==1||!value.access_token||!value.refresh_token)throw new Error("Código inválido");return value;}
  async function getSession(){
    if(!session)session=readSession();
    if(!session)return null;
    if(number(session.expires_at)*1000>Date.now()+60000)return session;
    if(!session.refresh_token){saveSession(null);return null;}
    var response=await request(SUPABASE_URL+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});
    if(!response.ok){saveSession(null);return null;}
    var fresh=response.data;fresh.expires_at=Math.floor(Date.now()/1000)+number(fresh.expires_in);saveSession(fresh);return fresh;
  }
  function lastSync(){var value=safeGet(LAST_SYNC_KEY),d=value?new Date(value):null;return d&&!isNaN(d)?d:null;}
  function when(value){if(!value)return "Nunca";try{return value.toLocaleString("es-US",{dateStyle:"medium",timeStyle:"short"});}catch(e){return value.toLocaleString();}}
  function redraw(){if(app&&app.screen&&app.screen()==="portafolio"&&app.render)app.render();}
  function escapeHtml(value){return String(value||"").replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function render(){var active=app&&app.session?app.session():session,status=busy?"Actualizando…":(message||("Última actualización: "+when(lastSync())));if(!active)return '<div class="sec">Sincronización con Public</div><div class="card public-sync"><div class="public-sync-head"><div class="public-logo">P</div><div><strong>Conectar Public</strong><p>Recibe un enlace seguro y mantén tus posiciones al día.</p></div></div><div class="public-sync-form"><input id="public-email" type="email" autocomplete="email" placeholder="Tu correo" value="'+escapeHtml(safeGet(EMAIL_KEY))+'"><button class="btn" onclick="PublicSync.signIn()">Enviar enlace</button></div><div class="public-sync-transfer"><p>¿El enlace se abrió en Safari? En Safari pulsa “Copiar para pantalla de inicio”; después pega el código aquí.</p><div class="public-sync-form"><input id="public-transfer" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Código de conexión"><button class="btn gh" onclick="PublicSync.useConnection()">Usar código</button></div></div>'+(message?'<div class="public-sync-status">'+escapeHtml(message)+'</div>':'')+'</div>';return '<div class="sec">Sincronización con Public</div><div class="card public-sync"><div class="public-sync-head"><div class="public-logo on">P</div><div><strong>Public conectado</strong><p>Las posiciones se revisan al abrir la app y cada 15 minutos.</p></div></div><div class="public-sync-actions"><button class="btn" '+(busy?'disabled':'')+' onclick="PublicSync.sync(true)">'+(busy?'Actualizando…':'Actualizar ahora')+'</button><button class="btn gh" onclick="PublicSync.copyConnection()">Copiar para pantalla de inicio</button><button class="btn gh" onclick="PublicSync.signOut()">Desconectar</button></div><div class="public-sync-status">'+escapeHtml(status)+'</div></div>';}
  async function signIn(){var field=document.getElementById("public-email"),email=field&&field.value.trim();if(!email){message="Escribe tu correo.";redraw();return;}safeSet(EMAIL_KEY,email);busy=true;message="Enviando enlace…";redraw();try{var redirect=location.origin+location.pathname,response=await request(SUPABASE_URL+"/auth/v1/otp?redirect_to="+encodeURIComponent(redirect),{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:email,create_user:true})});if(!response.ok){var error=new Error("Auth "+response.status);error.status=response.status;error.code=response.data&&response.data.error_code;throw error;}message="Revisa tu correo y abre el enlace de Supabase.";}catch(error){message=error&&(error.status===429||error.code==="over_email_send_rate_limit")?"Se enviaron varios enlaces. Espera unos minutos y vuelve a intentar.":"No se pudo enviar el enlace. Intenta de nuevo.";}busy=false;redraw();}
  async function signOut(){var active=await getSession();if(active)try{await request(SUPABASE_URL+"/auth/v1/logout",{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+active.access_token}});}catch(e){}saveSession(null);message="Public desconectado en este dispositivo.";redraw();}
  async function copyConnection(){try{var active=await getSession();if(!active)throw new Error("Sin sesión");var code=encodeSession(active);if(!navigator.clipboard||!navigator.clipboard.writeText)throw new Error("Sin portapapeles");await navigator.clipboard.writeText(code);message="Conexión copiada. Abre el ícono de Finanzas y pégala allí.";}catch(error){message="No se pudo copiar. Intenta otra vez desde Safari.";}redraw();}
  async function useConnection(){var field=document.getElementById("public-transfer"),code=field&&field.value.trim();if(!code){message="Pega primero el código copiado desde Safari.";redraw();return;}busy=true;message="Conectando este ícono…";redraw();try{saveSession(decodeSession(code));var active=await getSession();if(!active)throw new Error("Sesión vencida");if(field)field.value="";if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText("").catch(function(){});message="Public conectado en la pantalla de inicio.";busy=false;redraw();sync(true);return;}catch(error){saveSession(null);message="El código no es válido o ya venció.";}busy=false;redraw();}
  async function sync(showFeedback){if(busy||!app)return;var active=await getSession();if(!active){if(showFeedback){message="Primero conecta tu cuenta.";redraw();}return;}busy=true;if(showFeedback)message="Actualizando desde Public…";redraw();try{var response=await request(SUPABASE_URL+"/functions/v1/public-portfolio",{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+active.access_token,"Content-Type":"application/json"},body:"{}"}),result=response.data;if(!response.ok)throw {status:response.status};if(!result||!Array.isArray(result.accounts))throw new Error("Respuesta incompleta");var data=app.data();data.investments=mergePositions(data.investments,result.accounts,app.uid);app.save();var stamp=result.syncedAt||new Date().toISOString();safeSet(LAST_SYNC_KEY,stamp);message="Actualizado: "+data.investments.filter(function(i){return i.provider==="Public";}).length+" posiciones de Public.";if(showFeedback&&app.toast)app.toast("Public actualizado ✓");}catch(error){message=error&&error.status===403?"Esta cuenta no está autorizada.":"No se pudo actualizar. Intenta de nuevo.";}busy=false;redraw();}
  function applyTrm(data,rows){var row=rows&&rows[0],value=number(row&&row.valor),date=String(row&&row.vigenciadesde||"").slice(0,10);if(!data||value<2000||value>6000||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date))return false;data.settings=data.settings||{};data.prices=data.prices||[];var price=data.prices.filter(function(item){return item.unit==="COP"&&/d[oó]lar|TRM|USD/i.test(item.label||"");})[0];if(!price){price={id:"trm-oficial",label:"Dólar (TRM)",unit:"COP",history:[]};data.prices.unshift(price);}price.history=price.history||[];var old=price.history.filter(function(item){return item.d===date;})[0];if(old)old.p=value;else price.history.push({d:date,p:value});price.history.sort(function(a,b){return a.d.localeCompare(b.d);});data.settings.fx=value;return true;}
  async function syncTrm(force){if(!app)return;var last=number(safeGet(TRM_SYNC_KEY));if(!force&&last&&Date.now()-last<SIX_HOURS)return;try{var response=await request(TRM_URL);if(!response.ok||!applyTrm(app.data(),response.data))throw new Error("TRM inválida");safeSet(TRM_SYNC_KEY,String(Date.now()));app.save();if(app.refresh)app.refresh();}catch(error){}}
  function configure(value){rootWindow=value;var hash=new URLSearchParams((value.location.hash||"").replace(/^#/,"")),token=hash.get("access_token");if(token){var fresh={access_token:token,refresh_token:hash.get("refresh_token"),expires_in:number(hash.get("expires_in"))||3600,token_type:hash.get("token_type")||"bearer"};fresh.expires_at=Math.floor(Date.now()/1000)+fresh.expires_in;saveSession(fresh);value.history.replaceState({},document.title,value.location.pathname+value.location.search);message="Cuenta conectada. Actualizando Public…";}else session=readSession();}
  function init(options){app=options;if(app)app.setSession(session);var last=lastSync();getSession().then(function(active){if(active&&(!last||Date.now()-last.getTime()>FIFTEEN_MINUTES))sync(false);redraw();});syncTrm(false);setInterval(function(){if(app&&app.session())sync(false);},FIFTEEN_MINUTES);setInterval(function(){syncTrm(false);},SIX_HOURS);}
  return {configure:configure,init:init,render:render,signIn:signIn,signOut:signOut,copyConnection:copyConnection,useConnection:useConnection,sync:sync,syncTrm:syncTrm,applyTrm:applyTrm,encodeSession:encodeSession,decodeSession:decodeSession,mergePositions:mergePositions,flattenAccounts:flattenAccounts};
});
