(function(root,factory){
  var api=factory();
  if(typeof module!=="undefined"&&module.exports) module.exports=api;
  else { root.PublicSync=api; api.configure(root); }
})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  var SUPABASE_URL="https://qtmjogfivvwivenoiczx.supabase.co";
  var SUPABASE_KEY="sb_publishable_ltaNA7nnVozoSCOcZIjg";
  var LAST_SYNC_KEY="finanzas_public_last_sync_v1",EMAIL_KEY="finanzas_public_email_v1",FIFTEEN_MINUTES=15*60*1000;
  var client=null,app=null,busy=false,message="";
  function number(value){var parsed=Number(value);return Number.isFinite(parsed)?parsed:0;}
  function normalized(value){return String(value||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");}
  function typeFor(value){value=String(value||"").toUpperCase();if(value.indexOf("CRYPTO")>=0)return "Cripto";if(value.indexOf("ETF")>=0||value.indexOf("FUND")>=0)return "ETF";if(value==="CASH")return "Efectivo";return "Acción";}
  function similar(existing,position){var oldName=normalized(existing.name),symbol=normalized(position.symbol),fullName=normalized(position.name);if(!oldName)return false;return oldName===symbol||oldName===fullName||(oldName.length>3&&fullName.indexOf(oldName)>=0)||(fullName.length>3&&oldName.indexOf(fullName)>=0);}
  function flattenAccounts(accounts){var out=[];(accounts||[]).forEach(function(account){var accountId=String(account.accountId||"");(account.positions||[]).forEach(function(position){var instrument=position.instrument||{},symbol=String(instrument.symbol||instrument.name||"Posición");out.push({externalKey:accountId+":"+symbol+":"+String(instrument.type||""),symbol:symbol,name:String(instrument.name||symbol),type:typeFor(instrument.type),qty:number(position.quantity),currentValue:number(position.currentValue),costBase:number(position.costBasis&&position.costBasis.totalCost),currency:"USD",publicAccountType:String(account.accountType||"")});});var cash=number(account.cash);if(cash>0)out.push({externalKey:accountId+":CASH",symbol:"CASH",name:"Public · Efectivo",type:"Efectivo",qty:cash,currentValue:cash,costBase:cash,currency:"USD",publicAccountType:String(account.accountType||"")});});return out;}
  function mergePositions(existing,accounts,idFactory){var incoming=flattenAccounts(accounts),manual=(existing||[]).filter(function(i){return i.provider!=="Public";}),linked=(existing||[]).filter(function(i){return i.provider==="Public";}),result=manual.slice();incoming.forEach(function(position){var match=linked.filter(function(i){return i.externalKey===position.externalKey;})[0];if(!match)match=result.filter(function(i){return i.provider!=="Public"&&similar(i,position);})[0];var next=Object.assign({},match||{},position,{id:(match&&match.id)||(idFactory?idFactory():"public-"+position.externalKey),name:position.symbol==="CASH"?position.name:(position.symbol||position.name),provider:"Public",syncedAt:new Date().toISOString()});if(match){var index=result.indexOf(match);if(index>=0)result[index]=next;else result.push(next);}else result.push(next);});return result;}
  function safeGet(key){try{return localStorage.getItem(key)||"";}catch(e){return "";}}
  function safeSet(key,value){try{localStorage.setItem(key,value);}catch(e){}}
  function lastSync(){var value=safeGet(LAST_SYNC_KEY),d=value?new Date(value):null;return d&&!isNaN(d)?d:null;}
  function when(value){if(!value)return "Nunca";try{return value.toLocaleString("es-US",{dateStyle:"medium",timeStyle:"short"});}catch(e){return value.toLocaleString();}}
  function redraw(){if(app&&app.screen&&app.screen()==="portafolio"&&app.render)app.render();}
  function escapeHtml(value){return String(value||"").replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function render(){if(!client)return "";var session=app&&app.session?app.session():null,status=busy?"Actualizando…":(message||("Última actualización: "+when(lastSync())));if(!session)return '<div class="sec">Sincronización con Public</div><div class="card public-sync"><div class="public-sync-head"><div class="public-logo">P</div><div><strong>Conectar Public</strong><p>Recibe un enlace seguro y mantén tus posiciones al día.</p></div></div><div class="public-sync-form"><input id="public-email" type="email" autocomplete="email" placeholder="Tu correo" value="'+escapeHtml(safeGet(EMAIL_KEY))+'"><button class="btn" onclick="PublicSync.signIn()">Enviar enlace</button></div>'+(message?'<div class="public-sync-status">'+escapeHtml(message)+'</div>':'')+'</div>';return '<div class="sec">Sincronización con Public</div><div class="card public-sync"><div class="public-sync-head"><div class="public-logo on">P</div><div><strong>Public conectado</strong><p>Las posiciones se revisan al abrir la app y cada 15 minutos.</p></div></div><div class="public-sync-actions"><button class="btn" '+(busy?'disabled':'')+' onclick="PublicSync.sync(true)">'+(busy?'Actualizando…':'Actualizar ahora')+'</button><button class="btn gh" onclick="PublicSync.signOut()">Desconectar</button></div><div class="public-sync-status">'+escapeHtml(status)+'</div></div>';}
  async function signIn(){var field=document.getElementById("public-email"),email=field&&field.value.trim();if(!email){message="Escribe tu correo.";redraw();return;}safeSet(EMAIL_KEY,email);busy=true;message="Enviando enlace…";redraw();var result=await client.auth.signInWithOtp({email:email,options:{emailRedirectTo:location.origin+location.pathname}});busy=false;message=result.error?"No se pudo enviar: "+result.error.message:"Revisa tu correo y abre el enlace de Supabase.";redraw();}
  async function signOut(){await client.auth.signOut();message="Public desconectado en este dispositivo.";redraw();}
  async function sync(showFeedback){if(busy||!client||!app)return;var auth=await client.auth.getSession(),session=auth.data&&auth.data.session;if(!session){if(showFeedback){message="Primero conecta tu cuenta.";redraw();}return;}busy=true;if(showFeedback)message="Actualizando desde Public…";redraw();try{var result=await client.functions.invoke("public-portfolio",{body:{}});if(result.error)throw result.error;if(!result.data||!Array.isArray(result.data.accounts))throw new Error("Respuesta incompleta");var data=app.data();data.investments=mergePositions(data.investments,result.data.accounts,app.uid);app.save();var stamp=result.data.syncedAt||new Date().toISOString();safeSet(LAST_SYNC_KEY,stamp);message="Actualizado: "+data.investments.filter(function(i){return i.provider==="Public";}).length+" posiciones de Public.";if(showFeedback&&app.toast)app.toast("Public actualizado ✓");}catch(error){message=(error&&error.context&&error.context.status===403)?"Esta cuenta no está autorizada.":"No se pudo actualizar. Intenta de nuevo.";}busy=false;redraw();}
  function configure(rootWindow){if(!rootWindow.supabase||!rootWindow.supabase.createClient)return;client=rootWindow.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});}
  function init(options){app=options;if(!client)return;client.auth.getSession().then(function(result){if(app)app.setSession(result.data&&result.data.session);var last=lastSync();if(result.data&&result.data.session&&(!last||Date.now()-last.getTime()>FIFTEEN_MINUTES))sync(false);redraw();});client.auth.onAuthStateChange(function(event,session){if(app)app.setSession(session);if(event==="SIGNED_IN")setTimeout(function(){sync(false);},0);redraw();});setInterval(function(){if(app&&app.session())sync(false);},FIFTEEN_MINUTES);}
  return {configure:configure,init:init,render:render,signIn:signIn,signOut:signOut,sync:sync,mergePositions:mergePositions,flattenAccounts:flattenAccounts};
});
