const {test}=require('node:test');
const assert=require('node:assert/strict');
const F=require('../finance.js');
const PublicSync=require('../portfolio-bridge.js');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const empty=()=>({expenses:[],income:[],cafe_hours:[],assets:[],payables:[],cards:[],settings:{fx:4000,rate:17,weekly:250}});
test('week boundaries across years and daylight saving',()=>{assert.equal(F.monday('2027-01-03'),'2026-12-28');assert.equal(F.plus('2026-03-02',6),'2026-03-08');assert.equal(F.monday('2026-03-09'),'2026-03-09');});
test('weekly income includes salary plus all recorded income and linked tips once',()=>{let d=empty();d.cafe_hours=[{date:'2026-09-07',hours:6,tipId:'t'}];d.income=[{id:'t',date:'2026-09-07',source:'Propinas',amount:40},{date:'2026-09-08',source:'Pago café',amount:102}];let w=F.weekly(d,'2026-09-07');assert.equal(w.received,244);assert.equal(w.salary,102);assert.equal(w.tips,40);});
test('all six areas, legacy business tags and explicit overrides',()=>{assert.equal(F.area({category:'Saava'}),'Saava');assert.equal(F.area({venture:'Saava'}),'Saava');assert.equal(F.area({category:'Sequo'}),'Inversiones');assert.equal(F.area({category:'Ninas'}),'Inversiones');assert.equal(F.area({category:'Transporte'}),'Personal');F.areas.forEach(area=>assert.equal(F.area({area}),area));assert.equal(F.area({area:'Carro',category:'Saava'}),'Carro');});
test('cash expenses, COP conversion and budget allocations remain distinct',()=>{let d=empty();d.expenses=[{date:'2026-09-07',amount:4000000,currency:'COP',category:'Mercado',spread:4},{date:'2026-09-07',amount:900,area:'Saava'}];assert.equal(F.weekly(d,'2026-09-07').spent,1900);assert.equal(F.weekly(d,'2026-09-07','Personal').spent,1000);assert.equal(F.weekly(d,'2026-09-14').spent,0);assert.equal(F.alerts(d,'2026-09-14')[0].title,'Cerca del límite semanal');});
test('Colombia uses Saava margin and excludes car, investments, historical tips and wages',()=>{let d=empty();d.assets=[{name:'Jetta',type:'Vehículo',value:6000},{type:'Liquidez',value:8000000,currency:'COP'}];d.income=[{source:'Propinas',amount:9999}];d.cafe_hours=[{hours:100}];d.settings.colombia={saavaRevenue:2500,saavaCosts:800,livingCosts:1200,otherIncome:0,movingCost:500,reserveDebt:true};d.cards=[{balance:100}];let p=F.projection(d);assert.equal(p.net,500);assert.equal(p.initial,1400);assert.equal(p.months[11].balance,7400);assert.equal(p.tips,0);assert.equal(p.salary,0);});
test('deficit, zero income, negative initial cash and scheduled debt alerts',()=>{let d=empty();d.settings.colombia={livingCosts:100};let p=F.projection(d);assert.equal(p.runway,0);assert.equal(p.months[11].balance,-1200);d.payables=[{debtor:'A',amount:50,vence:'2026-09-14'},{debtor:'B',amount:50,vence:'fin de mes'}];d.cards=[{name:'Visa',balance:800,limit:1000}];const alerts=F.alerts(d,'2026-09-13');assert(alerts.some(a=>a.title==='Pago próximo'));assert.equal(alerts.filter(a=>a.target==='pagar').length,1);assert(alerts.some(a=>a.target==='tarjetas'));});
function app(){
 const nodes=new Map(),el=id=>{if(!nodes.has(id))nodes.set(id,{style:{},classList:{add(){},remove(){},toggle(){}},value:'',innerHTML:'',focus(){},querySelectorAll(){return []}});return nodes.get(id);};
 const doc={getElementById:el,querySelectorAll(){return []},addEventListener(){},documentElement:{setAttribute(){}}};
 const ctx=vm.createContext({Finance:F,document:doc,window:{scrollTo(){}},setTimeout(){},clearTimeout(){},console,sessionStorage:{getItem(){return null}},localStorage:{getItem(){return null},setItem(){}},confirm(){return true}});
 const dir=path.join(__dirname,'..'),html=fs.readFileSync(path.join(dir,'index.html'),'utf8');
 for(const m of html.matchAll(/<script(?: src="([^"]+)")?>([\s\S]*?)<\/script>/g)){if(m[1]){if(m[1].includes('planning'))vm.runInContext(fs.readFileSync(path.join(dir,m[1]),'utf8'),ctx);}else vm.runInContext(m[2],ctx);}
 ctx.D=ctx.normalize(JSON.parse(JSON.stringify(ctx.SEED)));ctx.curMonth='2026-09';return {ctx,el};
}
test('legacy JSON roundtrip preserves custom fields, balances, IDs and references',()=>{const {ctx}=app();const fixture={...empty(),custom:{kept:true},investments:[],income:[{id:'tip',source:'Propinas',date:'2026-09-07',amount:40,currency:'USD',custom:'keep'}],expenses:[{id:'e',date:'2026-09-07',desc:'Groceries',category:'Mercado',amount:80,currency:'USD',spread:4}],cafe_hours:[{id:'h',date:'2026-09-07',hours:6,tipId:'tip'}],assets:[{id:'car',name:'Jetta',type:'Vehículo',value:6000,currency:'USD'}]};let normalized=ctx.normalize(structuredClone(fixture));let roundtrip=ctx.normalize(JSON.parse(JSON.stringify(normalized)));assert.equal(JSON.stringify(roundtrip),JSON.stringify(normalized));assert.equal(roundtrip.custom.kept,true);assert.equal(roundtrip.income[0].custom,'keep');assert.equal(roundtrip.cafe_hours[0].tipId,'tip');assert.equal(roundtrip.assets.length,1);});
test('every screen renders with empty and populated JSON without NaN or undefined styles',()=>{const {ctx,el}=app();for(const populated of [false,true]){if(populated){ctx.D.assets.push({id:'car',name:'Jetta',type:'Vehículo',value:6000,currency:'USD'});ctx.D.settings.colombia={start:'2026-10',saavaRevenue:2500,saavaCosts:800,livingCosts:1200};ctx.D.income.push({id:'i',date:'2026-09-07',source:'Saava',venture:'Saava',amount:2500,currency:'USD'});ctx.D.expenses.push({id:'e',date:'2026-09-07',desc:'Inventario',area:'Saava',category:'Otros',amount:800,currency:'USD'});}for(const screen of Object.keys(ctx.TITLES).filter(s=>s!=='tarjeta')){ctx.go(screen);assert(!el('s-'+screen).innerHTML.includes('NaN'),screen);assert(!el('s-'+screen).innerHTML.includes('undefined'),screen);}}});
test('editing linked tips updates one income and Jetta registration is idempotent',()=>{const {ctx}=app();let h={id:'h',date:'2026-09-07',hours:6};ctx.D.cafe_hours.push(h);ctx.sincronizarPropina(h,40);ctx.sincronizarPropina(h,60);assert.equal(ctx.D.income.length,1);assert.equal(ctx.D.income[0].amount,60);assert.equal(ctx.D.income[0].id,h.tipId);ctx.registerJetta();ctx.registerJetta();assert.equal(ctx.D.assets.length,1);assert.equal(ctx.D.assets[0].value,6000);assert.equal(F.projection(ctx.D).liquid,0);});
test('saving and editing area preserves the original category and custom JSON fields',()=>{const {ctx,el}=app();ctx.D.expenses.push({id:'e',date:'2026-09-07',desc:'Gasolina',amount:20,currency:'USD',category:'Transporte',spread:4,custom:'retained'});el('f-amount').value='35';el('f-desc').value='Gasolina';el('f-date').value='2026-09-07';el('f-area').value='Carro';ctx._cur='USD';ctx._cat='Transporte';ctx.saveExp('e');assert.equal(ctx.D.expenses[0].area,'Carro');assert.equal(ctx.D.expenses[0].spread,4);assert.equal(ctx.D.expenses[0].category,'Transporte');assert.equal(ctx.D.expenses[0].custom,'retained');assert.equal(F.weekly(ctx.D,'2026-09-07','Personal').spent,0);assert.equal(F.weekly(ctx.D,'2026-09-07','Carro').spent,35);});

test('salary appears in Personal, monthly totals and alerts without modifying JSON',()=>{const {ctx,el}=app();ctx.D.cafe_hours=[{id:'h',date:'2026-09-07',hours:6}];ctx.D.income=[{id:'t',date:'2026-09-07',source:'Propinas',amount:40,currency:'USD'}];ctx.D.expenses=[{id:'e',date:'2026-09-07',desc:'Comida',category:'Mercado',amount:100,currency:'USD'}];const before=JSON.stringify(ctx.D);assert.equal(F.weekly(ctx.D,'2026-09-07','Personal').net,42);assert.equal(F.weekly(ctx.D,'2026-09-07','Saava').received,0);assert.equal(ctx.monthData('2026-09').inc,142);assert(!F.alerts(ctx.D,'2026-09-13').some(a=>a.target==='movs'));ctx.rResumen();assert(el('s-resumen').innerHTML.includes('Personal'));ctx.rMovs();assert(el('s-movs').innerHTML.includes('Salario por horas'));assert.equal(JSON.stringify(ctx.D),before);ctx.D.cafe_hours[0].hours=8;assert.equal(ctx.monthData('2026-09').inc,176);ctx.D.cafe_hours=[];assert.equal(ctx.monthData('2026-09').inc,40);});

test('Public sync updates matched holdings, keeps manual entries and removes stale Public positions',()=>{const existing=[{id:'voo',name:'VOO',type:'ETF',currentValue:1,costBase:1,currency:'USD',custom:'keep'},{id:'manual',name:'Private fund',type:'Otro',currentValue:20,costBase:20,currency:'USD'},{id:'stale',name:'OLD',provider:'Public',externalKey:'a:OLD:EQUITY',currentValue:9,costBase:9,currency:'USD'}];const accounts=[{accountId:'a',accountType:'BROKERAGE',cash:'5',positions:[{instrument:{symbol:'VOO',name:'Vanguard S&P 500 ETF',type:'ETF'},quantity:'2',currentValue:'1000',costBasis:{totalCost:'800'}}]}];const merged=PublicSync.mergePositions(existing,accounts,()=>"new");assert.equal(merged.length,3);const voo=merged.find(i=>i.name==='VOO');assert.equal(voo.id,'voo');assert.equal(voo.provider,'Public');assert.equal(voo.currentValue,1000);assert.equal(voo.costBase,800);assert.equal(voo.custom,'keep');assert(merged.some(i=>i.name==='Private fund'));assert(merged.some(i=>i.name==='Public · Efectivo'));assert(!merged.some(i=>i.name==='OLD'));});
